# Generated by Django 6.1.1 on 2026-09-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inscripciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropuestaCapacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('objetivo', models.TextField()),
                ('justificacion', models.TextField()),
            ],
        ),
    ]
